# Generated by Django 4.2.11 on 2024-05-08 13:43

import apps.ride_manager.models.vehicle
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("ride_manager", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Criado em"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Atualizado em"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Ativo"),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        max_length=255, verbose_name="Modelo do veículo"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        max_length=255, verbose_name="Cor do veículo"
                    ),
                ),
                ("plate", models.CharField(max_length=9, verbose_name="Placa")),
                (
                    "plate_picture",
                    models.ImageField(
                        upload_to=apps.ride_manager.models.vehicle.upload_path,
                        verbose_name="Imagem da placa",
                    ),
                ),
                (
                    "vehicle_picture",
                    models.ImageField(
                        upload_to=apps.ride_manager.models.vehicle.upload_path,
                        verbose_name="Imagem da veículo",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False, verbose_name="Verificado"
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ride_manager.person",
                        verbose_name="Pessoa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Veículo",
                "verbose_name_plural": "Veiculos",
            },
        ),
    ]
