# Generated by Django 4.2.11 on 2024-05-09 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("address_manager", "0001_initial"),
        ("ride_manager", "0003_affectedplace"),
    ]

    operations = [
        migrations.CreateModel(
            name="Voluntary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Criado em"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Atualizado em"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Ativo"),
                ),
                (
                    "any_destination",
                    models.BooleanField(
                        default=False, verbose_name="Qualquer destino?"
                    ),
                ),
                ("date", models.DateField(verbose_name="Data")),
                (
                    "work_shift",
                    models.CharField(
                        choices=[
                            ("MORNING", "Manhã"),
                            ("AFTERNOON", "Tarde"),
                            ("ALL_DAY", "Dia todo"),
                        ],
                        default="ALL_DAY",
                        max_length=255,
                        verbose_name="Turno de trabalho",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Disponível"),
                            ("IN_RESERVATION", "Combinando viagem"),
                            ("CLOSED", "Concluído"),
                        ],
                        default="OPEN",
                        max_length=255,
                        verbose_name="Status",
                    ),
                ),
                (
                    "destination",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ride_manager.affectedplace",
                        verbose_name="Local afetado",
                    ),
                ),
                (
                    "origin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="address_manager.city",
                        verbose_name="Cidade",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ride_manager.person",
                        verbose_name="Pessoa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Voluntário",
                "verbose_name_plural": "Voluntários",
            },
        ),
    ]
