# Generated by Django 4.2.11 on 2024-05-09 00:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("ride_manager", "0004_ride"),
    ]

    operations = [
        migrations.CreateModel(
            name="Passenger",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Criado em"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Atualizado em"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Ativo"),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                ("is_driver", models.BooleanField(verbose_name="É Motorista")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACCEPTED", "Aceito"),
                            ("REJECTED", "Rejeitado"),
                            ("PENDING", "Pendente"),
                        ],
                        max_length=255,
                        verbose_name="Status",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ride_manager.person",
                        verbose_name="Passageiro",
                    ),
                ),
                (
                    "ride",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ride_manager.ride",
                        verbose_name="Carona",
                    ),
                ),
            ],
            options={
                "verbose_name": "Passageiro",
                "verbose_name_plural": "Passageiros",
            },
        ),
    ]
