# Generated by Django 4.2.11 on 2024-05-09 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ride_manager", "0006_passenger"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Criado em"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Atualizado em"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Ativo"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendente"),
                            ("ACCEPTED", "Aceito"),
                            ("REFUSED", "Recusado"),
                        ],
                        default="PENDING",
                        max_length=255,
                        verbose_name="Status",
                    ),
                ),
                (
                    "ride",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ride_manager.ride",
                        verbose_name="Carona",
                    ),
                ),
                (
                    "voluntary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ride_manager.voluntary",
                        verbose_name="Voluntário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Convite",
                "verbose_name_plural": "Convites",
            },
        ),
    ]
