# Generated by Django 4.2.11 on 2024-05-09 14:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("ride_manager", "0007_invite"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhoneValidation",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Criado em"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Atualizado em"
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "integration_sid",
                    models.CharField(
                        editable=False,
                        max_length=36,
                        unique=True,
                        verbose_name="Sid da Integração",
                    ),
                ),
                (
                    "phone",
                    models.CharField(max_length=16, verbose_name="Telefone"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Ativo"),
                ),
            ],
            options={
                "verbose_name": "Validação de telefone",
                "verbose_name_plural": "Validações de telefone",
            },
        ),
    ]
