# Generated by Django 4.2.11 on 2024-05-09 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ride_manager", "0008_phonevalidation"),
    ]

    operations = [
        migrations.AddField(
            model_name="ride",
            name="whatspp_group_link",
            field=models.URLField(
                blank=True, null=True, verbose_name="Link do Grupo de WhatsApp"
            ),
        ),
    ]
