# Generated by Django 4.2.11 on 2024-05-06 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Term",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Criado em"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Atualizado em"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Ativo"),
                ),
                (
                    "version",
                    models.CharField(max_length=255, verbose_name="Versão"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("USE", "Termo de uso"),
                            ("PRIVACY", "Política de privacidade"),
                        ],
                        max_length=255,
                        verbose_name="Tipo de termo",
                    ),
                ),
                ("content", models.TextField(verbose_name="Conteúdo")),
            ],
            options={
                "verbose_name": "Termo",
                "verbose_name_plural": "Termos",
            },
        ),
        migrations.CreateModel(
            name="TermAcceptance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Criado em"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Atualizado em"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Ativo"),
                ),
                ("hashed_term", models.TextField(verbose_name="Hash do termo")),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="term_manager.term",
                        verbose_name="Termo",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aceite de Termo",
                "verbose_name_plural": "Aceites de Termo",
            },
        ),
    ]
