JAZZMIN_SETTINGS = {
    "icons": {
        "core": "fas fa-users-cog",
        "core.CustomUser": "fas fa-user",
        "core.CustomGroup": "fas fa-users",
        "ride_manager.Person": "fas fa-user",
        "ride_manager.Vehicle": "fas fa-car",
        "ride_manager.AffectedPlace": "fas fa-map-marker-alt",
        "ride_manager.Voluntary": "fas fa-hard-hat",
        "ride_manager.Ride": "fas fa-car-side",
        "ride_manager.Invite": "fas fa-inbox",
        "ride_manager.Passenger": "fas fa-user-friends",
        "ride_manager.PhoneValidation": "fas fa-phone",
        "address_manager.City": "fas fa-city",
        "address_manager.State": "fas fa-flag",
        "term_manager.Term": "fas fa-file-alt",
        "term_manager.TermAcceptance": "fas fa-file-signature",
    },
    "welcome_sign": "SOSRS-Caronas | Acesso Administrativo",
    "copyright": "SOSRS-Caronas",
    "order_with_respect_to": [
        "ride_manager",
        "address_manager",
        "core",
    ],
    "custom_css": "ride_manager/css/styles.css",
    "site_logo": "ride_manager/img/mini-logo.png",
    "login_logo": "ride_manager/img/logo.png",
}
